config/routes.rb
Rails.application.routes.draw do
  # root 'checkout#new'
  # resources :orders, only: [:new, :create]

  devise_for :users
  root 'events#index'
    
  resources :attendances
  resources :events
  resources :users
  
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <script src="https://js.stripe.com/v3/"></script>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <span class="navbar-brand mb-0 h1">EVENTBRITE</span>
  </div>
</nav>

<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <li class="nav-item">
    <button type="button" class="btn btn-secondary"><a class="nav-link active text-light" aria-current="page" <%= link_to "Home", root_path %></a></button>
    </li>
    <li class="nav-item">
    <button type="button" class="btn btn-secondary"><a class="nav-link text-light" href="<%= new_event_path %>">Create</a></button>   <!-- events#new-->
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= users_path %>">Users</a>
    </li>

    <ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "My profile", user_path(current_user.id) %>  <!-- users#show-->
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Log in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>
  </div>
</div>

    <%= yield %>
  </body>
</html>